//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazineProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_post
    {
        public int file_id { get; set; }
        public Nullable<int> article_id { get; set; }
        public string file_url { get; set; }
        public Nullable<System.DateTime> time_post { get; set; }
        public string file_status { get; set; }
        public Nullable<System.DateTime> time_public { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
