//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazineProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing_Manager
    {
        public string manager_id { get; set; }
        public string manager_password { get; set; }
        public string manager_name { get; set; }
        public string manager_email { get; set; }
        public string manager_phone { get; set; }
    }
}
