//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazineProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int review_id { get; set; }
        public Nullable<int> article_id { get; set; }
        public Nullable<int> display_code { get; set; }
        public string review_content { get; set; }
        public string review_name { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public Nullable<double> rating { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
