//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazineProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPostFile
    {
        public int file_id { get; set; }
        public Nullable<int> article_id { get; set; }
        public string file_url { get; set; }
        public Nullable<System.DateTime> time_post { get; set; }
        public string file_status { get; set; }
        public Nullable<System.DateTime> time_public { get; set; }
        public string student_id { get; set; }
        public Nullable<int> period_id { get; set; }
        public string article_tittle { get; set; }
        public string arrticle_content { get; set; }
        public string faculty_name { get; set; }
        public string article_avatar_img { get; set; }
        public string article_status { get; set; }
        public Nullable<System.DateTime> article_post_date { get; set; }
        public Nullable<System.DateTime> article_public_date { get; set; }
        public string student_name { get; set; }
        public string student_email { get; set; }
        public Nullable<System.DateTime> closure_post_date { get; set; }
        public string period_name { get; set; }
        public Nullable<int> display_code { get; set; }
        public string review_content { get; set; }
        public string review_name { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public Nullable<double> rating { get; set; }
        public string Expr1 { get; set; }
        public int Expr2 { get; set; }
        public int Expr3 { get; set; }
        public int review_id { get; set; }
        public string academic_id { get; set; }
        public Nullable<int> Expr4 { get; set; }
    }
}
